services:
  db:
    image: postgres:16
    container_name: udyam_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: udyamdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d udyamdb"]
      interval: 5s
      timeout: 3s
      retries: 30

  backend:
    build: ./backend
    container_name: udyam_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    command: sh -c "npx prisma migrate deploy || npx prisma db push && npm run dev"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: udyam_frontend
    restart: always
    environment:
      - VITE_API_URL=http://backend:5000/api
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app

volumes:
  db_data:
